import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
    AiFillTwitterCircle,
    AiFillLinkedin,
    AiFillYoutube,
} from "react-icons/ai";
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from "react";

export default function Home() {
    const [darkMode, setDarkMode] = useState(false);
    return (
        <div className={darkMode ? "dark" : ""}>
            <Head>
                <title>The Son Portfolio</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
                <section className=" min-h-screen">
                    <nav className="py-10 mb-12 flex justify-between">
                        <h1 className="text-2xl uppercase dark:text-gray-300">
                            theson
                        </h1>
                        <ul className="flex items-center">
                            <li>
                                <BsFillMoonStarsFill
                                    className="cursor-pointer text-2xl text-black dark:text-white"
                                    onClick={() => setDarkMode(!darkMode)}
                                />
                            </li>
                            <li>
                                <a
                                    href="#"
                                    className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                                >
                                    Resume
                                </a>
                            </li>
                        </ul>
                    </nav>
                    <div className="text-center p-10">
                        <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
                            The Son
                        </h2>
                        <h3 className="text-2xl py-2 md:text-3xl dark:text-gray-300">
                            Developer
                        </h3>
                        <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-gray-300">
                            Lorem ipsum dolor sit amet consectetur adipisicing
                            elit. Quam iure quas vel adipisci harum nobis
                            delectus dolorem veniam dolores blanditiis optio a
                            earum nam, assumenda non atque accusamus
                            exercitationem debitis!
                        </p>
                    </div>
                    <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
                        <AiFillTwitterCircle />
                        <AiFillLinkedin />
                        <AiFillYoutube />
                    </div>
                    <div className="relative bg-gradient-to-b from-teal-500 to-white rounded-full w-80 h-80 mt-20 mx-auto overflow-hidden md:h-96 md:w-96">
                        <Image src={deved} layout="fill" objectFit="cover" />
                    </div>
                </section>

                <section className="mt-10">
                    <div>
                        <h3 className="text-3xl py-1 dark:text-gray-300">
                            Services I offer
                        </h3>
                        <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-300">
                            Lorem ipsum, dolor sit amet consectetur adipisicing
                            elit. Deserunt{" "}
                            <span className="text-teal-500">agency</span>{" "}
                            nesciunt et iure quae atque consequatur accusamus
                            illum{" "}
                            <span className="text-teal-500">dignissimos</span>{" "}
                            est blanditiis earum similique quibusdam harum enim
                            sapiente, deleniti ratione doloribus voluptatibus.
                        </p>
                        <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-300">
                            Lorem ipsum dolor sit amet consectetur adipisicing
                            elit. Totam, ea accusamus unde asperiores magnam
                            saepe libero tempore.
                        </p>
                    </div>
                    <div className="lg:flex gap-10">
                        <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:text-gray-300 dark:bg-gray-800">
                            <Image
                                src={design}
                                width={100}
                                height={100}
                                className="mx-auto"
                            />
                            <h3 className="text-lg font-medium pt-8 pb-2">
                                Beautiful design
                            </h3>
                            <p className="py-2">
                                Lorem ipsum dolor sit amet consectetur
                                adipisicing elit. Sapiente quia autem, ipsum
                            </p>
                            <h4 className="py-4 text-teal-600">
                                Designs tools I use
                            </h4>
                            <p className="text-gray-800 py-1 dark:text-gray-600">
                                Photoshop
                            </p>
                            <p className="text-gray-800 py-1 dark:text-gray-600">
                                Figma
                            </p>
                            <p className="text-gray-800 py-1 dark:text-gray-600">
                                Illustrator
                            </p>
                        </div>
                        <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:text-gray-300 dark:bg-gray-800">
                            <Image
                                src={code}
                                width={100}
                                height={100}
                                className="mx-auto"
                            />
                            <h3 className="text-lg font-medium pt-8 pb-2">
                                Coding
                            </h3>
                            <p className="py-2">
                                Lorem ipsum dolor sit amet consectetur
                                adipisicing elit. Sapiente quia autem, ipsum
                            </p>
                            <h4 className="py-4 text-teal-600">
                                IDE that I use
                            </h4>
                            <p className="text-gray-800 py-1 dark:text-gray-600">
                                WebStorm
                            </p>
                            <p className="text-gray-800 py-1 dark:text-gray-600">
                                VSCode
                            </p>
                            <p className="text-gray-800 py-1 dark:text-gray-600">
                                Intellij
                            </p>
                        </div>
                        <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:text-gray-300 dark:bg-gray-800">
                            <Image
                                src={consulting}
                                width={100}
                                height={100}
                                className="mx-auto"
                            />
                            <h3 className="text-lg font-medium pt-8 pb-2">
                                Consulting
                            </h3>
                            <p className="py-2">
                                Lorem ipsum dolor sit amet consectetur
                                adipisicing elit. Sapiente quia autem, ipsum
                            </p>
                            <h4 className="py-4 text-teal-600">
                                Consulting tools I use
                            </h4>
                            <p className="text-gray-800 py-1 dark:text-gray-600">
                                Word
                            </p>
                            <p className="text-gray-800 py-1 dark:text-gray-600">
                                Excel
                            </p>
                            <p className="text-gray-800 py-1 dark:text-gray-600">
                                Draw.io
                            </p>
                        </div>
                    </div>
                </section>

                <section>
                    <div className=" dark:text-gray-300">
                        <h3 className="text-3xl py-1 ">Portfolio</h3>
                        <p className="text-md py-2 leading-8 text-gray-800  dark:text-gray-300">
                            Lorem ipsum, dolor sit amet consectetur adipisicing
                            elit. Deserunt{" "}
                            <span className="text-teal-500">agency</span>{" "}
                            nesciunt et iure quae atque consequatur accusamus
                            illum{" "}
                            <span className="text-teal-500">dignissimos</span>{" "}
                            est blanditiis earum similique quibusdam harum enim
                            sapiente, deleniti ratione doloribus voluptatibus.
                        </p>
                        <p className="text-md py-2 leading-8 text-gray-800  dark:text-gray-300">
                            Lorem ipsum dolor sit amet consectetur adipisicing
                            elit. Totam, ea accusamus unde asperiores magnam
                            saepe libero tempore.
                        </p>
                    </div>
                    <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
                        <div className="basis-1/3 flex-1">
                            <Image
                                src={web1}
                                className="rounded-xl object-cover"
                                width="100%"
                                height="100%"
                                layout="responsive"
                            />
                        </div>
                        <div className="basis-1/3 flex-1">
                            <Image
                                src={web2}
                                className="rounded-xl object-cover"
                                width="100%"
                                height="100%"
                                layout="responsive"
                            />
                        </div>
                        <div className="basis-1/3 flex-1">
                            <Image
                                src={web3}
                                className="rounded-xl object-cover"
                                width="100%"
                                height="100%"
                                layout="responsive"
                            />
                        </div>
                        <div className="basis-1/3 flex-1">
                            <Image
                                src={web4}
                                className="rounded-xl object-cover"
                                width="100%"
                                height="100%"
                                layout="responsive"
                            />
                        </div>
                        <div className="basis-1/3 flex-1">
                            <Image
                                src={web5}
                                className="rounded-xl object-cover"
                                width="100%"
                                height="100%"
                                layout="responsive"
                            />
                        </div>
                        <div className="basis-1/3 flex-1">
                            <Image
                                src={web6}
                                className="rounded-xl object-cover"
                                width="100%"
                                height="100%"
                                layout="responsive"
                            />
                        </div>
                    </div>
                </section>
            </main>
        </div>
    );
}
